### PR TITLE
First review

### PR DESCRIPTION
**Pull request by jsejcksn**
An MVP is already committed, but this PR will finalize the first draft of the module(s), including basic documentation.

Ref: [Neocities API Documentation](https://neocities.org/api)

### CODE REVIEW

**Comment by jsejcksn** [comment]
Note: the import URLs in the README examples won't work until this PR is merged and a v`0.1.0` release is created to update `deno.land/x/neocities`.

**Review by akeithly — COMMENTED** [review]
LGTM

I think I would prefer seeing the functional options in line instead of at the end. Note: Perhaps I would have better feedback if I was following the instructions as if to execute them.

**Comment by jsejcksn** [comment]
@akeithly Thanks for the read. I like the interleaved idea. The functional exports are obviously not an afterthought (but they were in regard to creation of the documentation.) I'll definitely think on this more.

**Comment by jsejcksn** [comment]
@kyledrake I'm not sure if the types are 100% correct: I created them from response values that I received during experimentation. Do they look correct to you? Feel free to leave any comments here (or directly on future commits if this is already merged). _By the way, I emailed you about including this in the client listing in the API docs._

**Pull request merged**
